/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nuevoClienteServidor;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javafx.embed.swing.JFXPanel;
import javafx.scene.media.MediaPlayer;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 * Class that represents a video playback window.
 * This window plays a video file using Windows Media Player.
 * The name of the video file is provided to the constructor.
 * Playback stops automatically when you close the window.
 *
 * @author Jocelyn,Jeison,Carlos,Josep,Adrian
 */
public class PlayerVideo extends javax.swing.JFrame {

    private MediaPlayer mediaPlayer;
    private final String Video;

    private final JFXPanel jfxpanel = new JFXPanel();
    
     backgroundPanel fondo = new backgroundPanel();
     
     /**
 * Constructor of the PlayerVideo class.
 * Initializes a new PlayerVideo instance to play the specified video file.
 *
 * @param Video The name of the video file to play.
 */
    public PlayerVideo(String Video) {
        this.Video = Video; 
        this.setContentPane(fondo);
        initComponents();
        
        setTitle("Reproduciendo " + Video);
        File file = new File("download/" + Video);

        if (file != null) {
            String relativePath = file.toURI().toString();
            String abosolutePath = relativePath.substring(6);
            System.out.println("Direccion del archivo: "+abosolutePath);
           
            playVideoWithWindows(abosolutePath);
        }
        
        setResizable(false);
        setLocationRelativeTo(null);
        this.setLocationRelativeTo(null);

        setupComponents(Video);
        initializeMediaPlayer(Video);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                stopVideo();
                dispose();
            }
        });
    }
 /**
 * Static method to play a video file using Windows Media Player.
 *
 * @param videoFilePath The path of the video file to play.
 */
    public static void playVideoWithWindows(String videoFilePath) {
        System.out.println(videoFilePath);
        try {
            File videoFile = new File(videoFilePath);
            if (!videoFile.exists()) {
                System.out.println("El archivo de video no existe: " + videoFilePath);
                return;
            }

            
            ProcessBuilder builder = new ProcessBuilder("cmd.exe", "/c", "start", "wmplayer", videoFilePath);
            builder.start();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void initializeMediaPlayer(String videoFilePath) {

    }

    private void setupComponents(String Video) {
        PlayVideo.setText(Video);
    }

    private void stopVideo() {
        if (mediaPlayer != null) {
            mediaPlayer.stop();
            mediaPlayer.dispose();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlayVideo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PlayVideo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PlayVideo.setText("                                       Video ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PlayVideo, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(PlayVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PlayVideo;
    // End of variables declaration//GEN-END:variables
/**
 * Custom class that extends JPanel and is used to display a background image on a panel.
 * Cita: Maxita. (2015, 15 de octubre). How to Implement 
 * Bubble Sort in Java [Video]. YouTube. https://youtu.be/CfKlAHInank?si=XD_Du-OgDjimZ9OD
 */
class backgroundPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {

            imagen = new ImageIcon(getClass().getResource("/Imagenes/fondoAzul.png")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }

    }
}
